var menu = {
	en: {
        "step": "Step",
		"of": "of",
		"warning": "WARNING: Don't play this game if you experience any of the following health problems or symptoms:",
		"seizures": "seizures, Epilepsy, gaming addiction or aggressive Behaviors.",
		"continue": "Continue",
		"lastclick": "Start Game",
		"skills": "Your Character will start with one special skill.",
		"mskills": "More skills can be unlocked by gaining experience",
		"a1": "Assassin",
		"a2": "Mage",
		"a3": "Warrior",
		"players": "We have detected <span class='yellow rannum'># </span>online players in <span class='yellow country'>#</span>",
		"gamemode1": "This game can be played solo or online.",
		"gamemode2": "Select Game Mode",
		"solo": "play solo",
		"online": "play online",
		"browser": "Browser Compatibility Detection",
		"compatible": "<span class='brname yellow'>#</span> is compatible",
		"nodownload": "No Download is Required."
	},
	fr: {
		"step": "Étape",
		"of": "De",
		"warning": "ATTENTION: Ne jouez pas à ce jeu si vous souffrez de l'un des problèmes de santé suivants:",
		"seizures": "Épilepsie, Problèmes cardiaques, Dépendance aux jeux vidéos,<br /> Comportements agressifs",
		"continue": "Continuer",
		"lastclick": "Continuer",
		"skills": "Votre personnage commencera avec une compétence spéciale.",
		"mskills": "Plus de compétences pourront être débloquées en gagnant des points d'expérience.",
		"a1": "Assassin",
		"a2": "Mage",
		"a3": "Guerrier",
		"players": "<span class='yellow rannum'># </span> joueurs en ligne dans votre pays: <span class='yellow country'>#</span>",
		"gamemode1": "Ce jeu peut être joué en mode solo ou en ligne.",
		"gamemode2": "Sélectionner votre mode de jeu",
		"solo": "JOUER SOLO",
		"online": "JOUER EN LIGNE",
		"browser": "Vérification de la compatibilité du navigateur web",
		"compatible": "<span class='brname yellow'>#</span> est compatible",
		"nodownload": "Aucun téléchargement n'est requis."
	},
	de: {
		"step": "Schritt",
		"of": "Von",
		"warning": "WARNUNG: Bitte spielen Sie das Spiel nicht, wenn Sie eine der folgenden gesundheitlichen Probleme oder Symptome aufweisen:",
		"seizures": "Anfälle, Epilepsie, Spielsucht oder aggressive Verhaltensweisen.",
		"continue": "Fortfahren",
		"lastclick": "abspielen",
		"skills": "Dein Charakter beginnt mit einer besonderen Fähigkeit.",
		"mskills": "Mehr Fähigkeiten können durch Erfahrungserweiterung erschlossen werden",
		"a1": "Attentäter",
		"a2": "Magier",
		"a3": "Krieger",
		"players": "Wir haben <span class='yellow rannum'># </span>Online-Spieler in <span class='yellow country'>#</span> gefunden",
		"gamemode1": "Dieses Spiel kann alleine oder online gespielt werden.",
		"gamemode2": "Wählen Sie einen Spielmodus",
		"solo": "SOLO SPIELEN",
		"online": "ONLINE SPIELEN",
		"browser": "Browser Kompatibilitätserkennung",
		"compatible": "<span class='brname yellow'>#</span> ist kompatibel",
		"nodownload": "Kein Download erforderlich"
	},
	es: {
		"step": "Paso",
		"of": "de",
		"warning": "Advertencia: No juegue este juego si experimenta alguno de los siguientes síntomas o problemas de salud:",
		"seizures": "Convulsiones, Epilelpsia, adicción al juego o comportamientos agresivos",
		"continue": "Continuar",
		"lastclick": "Empezar el juego",
		"skills": "Su personaje comenzará con una habilidad especial",
		"mskills": "Se pueden desbloquear más habilidades ganando experiencia",
		"a1": "Asesino",
		"a2": "Mago",
		"a3": "Guerrero",
		"players": "Hemos detectado <span class='yellow rannum'># </span> jugadores en línea en <span class='yellow country'>#</span>",
		"gamemode1": "Este juego se puede jugar sólo o en línea",
		"gamemode2": "Selecciona el modo de juego",
		"solo": "Jugar en solitario",
		"online": "Jugar en línea",
		"browser": "Detección de compatibilidad del navegador",
		"compatible": "<span class='brname yellow'>#</span> es compatible",
		"nodownload": "No se requiere descarga"
	},
	it: {
		"step": "Passo",
		"of": "di",
		"warning": "Avvertenza: non giocare se soffri di alcuni di questi sintomi o problemi di salute:",
		"seizures": "Convulsioni, epilessia, dipendenza dal gioco o comportamento aggressivo",
		"continue": "Continua",
		"lastclick": "Inizia a giocare",
		"skills": "Il tuo personaggio inizierà con un'abilità speciale",
		"mskills": "Si possono sbloccare nuove abilità guadagnandpo esperienza",
		"a1": "Assassino",
		"a2": "Mago",
		"a3": "Guerriero",
		"players": "Abbiamo trovato <span class='yellow rannum'># </span> giocatori in linea in <span class='yellow country'>#</span>",
		"gamemode1": "Puoi giocare a questo gioco in solitario o online",
		"gamemode2": "Seleziona la modalità di gioco",
		"solo": "Gioca da solo",
		"online": "Gioca online",
		"browser": "Controllando la compatibilità del browser",
		"compatible": "<span class='brname yellow'>#</span> è compatibile",
		"nodownload": "Nessun download richiesto"
	},
	tr: {
		"step": "Adım",
		"of": "/",
		"warning": "UYARI: Eğer aşağıdaki sağlık sorunları yada semptomlar üzerinizde gözleniyorsa bu oyunu oynamayın :",
		"seizures": "felç, epilepsi, oyun bağımlılığı yada agresif davranışlar.",
		"continue": "Devam",
		"lastclick": "Oyuna Başla",
		"skills": "Karakteriniz oyuna bir adet özel beceriyle birlikte başlayacaktır.",
		"mskills": "Diğer becerilerin kilitleri tecrübe kazanıldıkça açılacaktır.",
		"a1": "Suikastçi",
		"a2": "Büyücü",
		"a3": "Savaşçı",
		"players": "<span class='yellow country'>#</span>’de <span class='yellow rannum'># </span> çevrimiçi oyuncu tespit ettik.",
		"gamemode1": "Bu oyun tek kişi yada online olarak oynanılabilir.",
		"gamemode2": "Oyun modu seç",
		"solo": "Tek başına oyna",
		"online": "Online oyna",
		"browser": "Tarayıcı uygunluk belirlemesi",
		"compatible": "<span class='brname yellow'>#</span> uygun",
		"nodownload": "İndirme gerektirmiyor."
	},
	pl: {
		"step": "Etap",
		"of": "z",
		"warning": "OSTRZEŻENIE: Nie graj w tę grę, jeśli doświadczasz któregokolwiek z poniższych problemów zdrowotnych lub objawów:",
		"seizures": "napady, padaczka, uzależnienie od gier lub agresywne zachowania.",
		"continue": "Kontynuuj",
		"lastclick": "Rozpocznij grę",
		"skills": "Twoja postać zacznie od jednej specjalnej umiejętności.",
		"mskills": "Więcej umiejętności można odblokować poprzez zdobycie doświadczenia",
		"a1": "Asasyna",
		"a2": "Maga",
		"a3": "Wojownik",
		"players": "Wykryliśmy <span class='yellow rannum'># </span> graczy online w <span class='yellow country'>#</span>",
		"gamemode1": "W tę grę można grać solo lub online.",
		"gamemode2": "Wybierz tryb gry",
		"solo": "Grać solo",
		"online": "Grać online",
		"browser": "Wykrywanie zgodności z przeglądarką",
		"compatible": "<span class='brname yellow'>#</span> jest kompatybilny",
		"nodownload": "Nie jest wymagane żadne pobieranie."
	},
	sv: {
		"step": "Steg",
		"of": "av",
		"warning": "VARNING: Spela inte det här spelet om du upplever något av följande hälsoproblem eller symptom:",
		"seizures": "Epilepsi, spelberoende eller agressivt uppförande.",
		"continue": "Fortsätt",
		"lastclick": "Starta Spel",
		"skills": "Din karaktär börjar med en specialförmåga.",
		"mskills": "Fler förmågor kan låsas upp genom att få erfarenhetspoäng.",
		"a1": "Lönnmördare",
		"a2": "Magiker",
		"a3": "Krigare",
		"players": "Vi har upptäckt <span class='yellow rannum'># </span>spelare online i <span class='yellow country'>#</span>",
		"gamemode1": "Det här spelet kan spelas enasm eller online.",
		"gamemode2": "Välj Spelläge",
		"solo": "spela solo",
		"online": "spela online",
		"browser": "Upptäcker Webbläsarens Kompatibilitet",
		"compatible": "<span class='brname yellow'>#</span> är kompatibel",
		"nodownload": "Ingen Nerladdning Krävs."
	},
	no: {
		"step": "Steg",
		"of": "av",
		"warning": "ADVARSEL: Ikke spill dette spillet dersom du opplever noen av følgende helseproblemer eller symptomer:",
		"seizures": "anfall, epilepsi, spillavhengighet eller aggressiv adferd.",
		"continue": "Fortsett",
		"lastclick": "Start spill",
		"skills": "Din karakter begynner med en spesiell ferdighet.",
		"mskills": "Flere ferdigheter kan låses opp ved å få erfaring",
		"a1": "Snikmorder",
		"a2": "Trollmann",
		"a3": "Kriger",
		"players": "Vi har oppdaget <span class='yellow rannum'># </span> online spillere i <span class='yellow country'>#</span>",
		"gamemode1": "Dette spillet kan spilles solo eller online.",
		"gamemode2": "Velg spillmodus",
		"solo": "spill solo",
		"online": "spill online",
		"browser": "Nettleser kompatibilitet deteksjon",
		"compatible": "<span class='brname yellow'>#</span> er kompatibel",
		"nodownload": "Ingen nedlasting er nødvendig."
	},
	fi: {
		"step": "Vaihe",
		"of": "of",
		"warning": "VAROITUS: Älä pelaa tätä peliä, jos sinulla on jotain seuraavista terveysongelmista tai -oireiista:",
		"seizures": "Sydänkohtaus, epilepsia, peliriippuvuus tai aggressiivinen käytös.",
		"continue": "Jatka",
		"lastclick": "Aloita peli",
		"skills": "Hahmollasi on aluksi yksi erikoistaito.",
		"mskills": "Voit avata lisää taitoja hankkimalla kokemusta",
		"a1": "Salamurhaaja",
		"a2": "Velho",
		"a3": "Soturi",
		"players": "Olemme havainneet <span class='yellow rannum'># </span>verkkopelaajaa <span class='yellow country'>#</span>",
		"gamemode1": "Tätä peliä voi pelata yksinpelinä tai verkossa.",
		"gamemode2": "Valitse pelimuoto",
		"solo": "Pelaa yksinpelinä",
		"online": "Pelaa verkossa",
		"browser": "Tunnistetaan selaimen yhteensopivuutta",
		"compatible": "<span class='brname yellow'>#</span> on yhteensopiva",
		"nodownload": "Latausta ei vaadita."
	},
	da: {
		"step": "Step",
		"of": "af",
		"warning": "ADVARSEL: Spil ikke dette spil hvis du oplever nogle af de følgende problemer eller symptomer:",
		"seizures": "anfald, epilepsi, spilleafhængighed eller aggressiv opførsel",
		"continue": "Fortsæt",
		"lastclick": "Start spil",
		"skills": "Din karakter starter med et special skill",
		"mskills": "Flere skills kan oplåses ved mere erfaring",
		"a1": "Snigmorder",
		"a2": "Troldmand",
		"a3": "Kriger",
		"players": "Vi har opdaget <span class='yellow rannum'># </span>online players in <span class='yellow country'>#</span>",
		"gamemode1": "Dette spil kan spilles alene eller online",
		"gamemode2": "Vælg game mode",
		"solo": "Spil alene",
		"online": "Spil online",
		"browser": "Browser Kompatibilitetsdetektion",
		"compatible": "<span class='brname yellow'>#</span> is compatible",
		"nodownload": "Download er ikke påkrævet"
	}
};
